services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: clean_api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Server=sqlserver,1433;Database=CleanCqrsDemo;User Id=sa;Password=YourStrongPass123;TrustServerCertificate=True;"
    ports:
      - "8080:8080"
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: clean_sql
    platform: linux/amd64         # important on Apple Silicon
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPass123"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433'"]
      interval: 10s
      timeout: 5s
      retries: 30
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
